#!/bin/bash

# run_profiling  polymer_builder_driver.py C -cru_num 10 -mol_num 10 -seed 5678

# The profiling process is always successful, but virtualize the results with empty stderr only
# https://stackoverflow.com/questions/11027679/capture-stdout-and-stderr-into-different-variables
SCRIPT_ARGS="run_nemd -m cProfile -o nemd.profile $*"

{
    IFS=$'\n' read -r -d '' CAPTURED_STDERR;
    IFS=$'\n' read -r -d '' CAPTURED_STDOUT;
} < <((printf '\0%s\0' "$($SCRIPT_ARGS)" 1>&2) 2>&1)

echo 'Here is the captured stdout:'
echo "${CAPTURED_STDOUT}"
echo

echo 'And here is the captured stderr:'
echo "${CAPTURED_STDERR}"
echo

if [ -z "$CAPTURED_STDERR" ]; then
    SCRIPT_ARGS="snakeviz nemd.profile"
    echo "Running $SCRIPT_ARGS"
    eval "$SCRIPT_ARGS"
    exit
fi